# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ugBos_JRLJKWPeHRYHnNugHfYblmndoK
"""

import numpy as np
import matplotlib . pyplot as plt
import seaborn as sns # Import seaborn
# Set the seaborn style
sns.set_theme ( style ="whitegrid")

# This defines the step size h for the numerical computation .
h = 0.1
# This creates a grid x from 0 to 2 with intervals of h.
x = np . arange (0 , 2*np .pi , h)
# This computes the cosine function values for each point in the
# grid x.
y = np . sin (x)
# This calculates the forward differences of y ' vector ' divided by
# h, which is an ap pr ox ima ti on of
# the derivative of cos (x).
forward_diff = np . diff ( y)/h
# This defines a new grid x_diff that corresponds to the forward
# differences . It excludes the last
# point of x since np. diff reduces
# the array size by one .
x_diff = x[:-1]
# This calculates the exact solution for the derivative of cos (x),
# which is -sin (x) , evaluated at
# x_diff .
exact_solution = np . cos ( x_diff ) # Changed from sin(x_diff) to cos(x_diff) since derivative of sin(x) is cos(x)
# This code block creates a plot showing both the finite difference
# approximation and the exact
# solution.
plt . figure ( figsize = ( 12 , 8))
plt . plot ( x_diff , forward_diff , '--', \
label = 'Finite difference approximation ')
plt . plot ( x_diff , exact_solution , \
label = 'Exact solution ')
plt . legend ()
plt . show ()
# Finally , this computes the maximum error between the numerical
# derivative and the exact solution
# , then prints the result .
max_error = max ( abs ( exact_solution - forward_diff ))
print ( max_error )

